## Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
# Create a simple dataframe
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']
})

In [5]:
df.head()

   Color
0    Red
1   Blue
2  Green
3   Blue
4    Red

In [6]:
# create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [7]:
# perform one-hot encoding
encoded = encoder.fit_transform(df[['Color']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [8]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoder_df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [9]:
encoder.transform([[ 'Green' ]]).toarray()

/Users/vmangla/Documents/Vaibhav/Programming/Python/Python_ML_DL/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 1., 0.]])

In [10]:
encoder.transform([[ 'Blue' ]]).toarray()

/Users/vmangla/Documents/Vaibhav/Programming/Python/Python_ML_DL/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [11]:
pd.concat([df, encoder_df], axis=1)

   Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1   Blue         1.0          0.0        0.0
2  Green         0.0          1.0        0.0
3   Blue         1.0          0.0        0.0
4    Red         0.0          0.0        1.0

In [12]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [13]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [14]:
lbl_encoder.fit_transform(df['Color'])

array([2, 0, 1, 0, 2])

In [17]:
lbl_encoder.transform([['Green']])

/Users/vmangla/Documents/Vaibhav/Programming/Python/Python_ML_DL/.venv/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [18]:
lbl_encoder.transform([['Blue']])

/Users/vmangla/Documents/Vaibhav/Programming/Python/Python_ML_DL/.venv/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

### Ordinal Encoding
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
df = pd.DataFrame({
    'Size': ['Small', 'Medium', 'Large', 'Medium', 'Small', 'Large']
})

In [22]:
df

     Size
0   Small
1  Medium
2   Large
3  Medium
4   Small
5   Large

In [23]:
#  Create an instance of OrdinalEncoder and fit_transform the data
ord_encoder = OrdinalEncoder(categories=[['Small', 'Medium', 'Large']])
ord_encoded = ord_encoder.fit_transform(df[['Size']])
ord_encoded

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [26]:
ord_encoder.transform([['Medium']])

/Users/vmangla/Documents/Vaibhav/Programming/Python/Python_ML_DL/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])